<a href="https://colab.research.google.com/github/Aryan123Yad/numpy-practice/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

pandas series

a

 series is a one dimension lebeled array capable of holding any data type. The axis labels are collectively called the index

creating series
there are multiple ways to create a pandas series

In [2]:
import numpy as np
import pandas as pd

In [3]:
labels = ['a','b','c']
my_list = [10,20,30]
arr = np.array(my_list)
d = {'a':10,'b':20,'c':30}

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [6]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [8]:
import numpy as np
import pandas as pd

data frame creating

In [9]:
import numpy as np
import pandas as pd

In [10]:
data = {
    'name':['john','rahul','shubham','rupesh'],
    'age':[28,34,54,55],
    'city':['new york', 'paris','london','bali'],
    'salary':['50000','30000','45000','34000']
}
df= pd.DataFrame(data)

In [11]:
df

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

In [12]:
data_list = {
    'name':['john','rahul','shubham','rupesh'],
    'age':[28,34,54,55],
    'city':['new york', 'paris','london','bali'],
    'salary':['50000','30000','45000','34000']
}
df2= pd.DataFrame(data_list)
columns = ['name','age','city','salary']
df2 = pd.DataFrame(data_list,columns=columns)
df2

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

In [13]:
df2

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

selection and indexing of colums

In [14]:
df2

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

In [15]:
df2[['age','salary']]

   age salary
0   28  50000
1   34  30000
2   54  45000
3   55  34000

creating a new column

In [16]:
df2["designation"] = ["docter","engineer","doctor","engineer"]
df2

      name  age      city salary designation
0     john   28  new york  50000      docter
1    rahul   34     paris  30000    engineer
2  shubham   54    london  45000      doctor
3   rupesh   55      bali  34000    engineer

remove the column

In [17]:
df2

      name  age      city salary designation
0     john   28  new york  50000      docter
1    rahul   34     paris  30000    engineer
2  shubham   54    london  45000      doctor
3   rupesh   55      bali  34000    engineer

In [18]:
df2.drop('designation',axis =1)

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

In [19]:
df2

      name  age      city salary designation
0     john   28  new york  50000      docter
1    rahul   34     paris  30000    engineer
2  shubham   54    london  45000      doctor
3   rupesh   55      bali  34000    engineer

In [20]:
df2.drop('designation',axis =1,inplace=True)

In [21]:
df2

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

In [22]:
df2.drop(2,axis=0)

     name  age      city salary
0    john   28  new york  50000
1   rahul   34     paris  30000
3  rupesh   55      bali  34000

In [23]:
df2.drop(["city","salary"],axis =1)

      name  age
0     john   28
1    rahul   34
2  shubham   54
3   rupesh   55

In [24]:
df2

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

selecting the row

In [25]:
df2.loc[[0,1]]

    name  age      city salary
0   john   28  new york  50000
1  rahul   34     paris  30000

In [26]:
df.iloc[3]

name      rupesh
age           55
city        bali
salary     34000
Name: 3, dtype: object

In [27]:
df.loc[[0,1]][["city","salary"]]

       city salary
0  new york  50000
1     paris  30000

conditional selection

In [28]:
df2

      name  age      city salary
0     john   28  new york  50000
1    rahul   34     paris  30000
2  shubham   54    london  45000
3   rupesh   55      bali  34000

In [29]:
#i only want to see those people whose age is above i 30

In [30]:
df2[df2["age"]>30]

      name  age    city salary
1    rahul   34   paris  30000
2  shubham   54  london  45000
3   rupesh   55    bali  34000

In [31]:
#i wamt to people whose age is 30 and their city must be paris

In [32]:
df2[(df2["age"]==30) & (df2["city"]=="bali")]

Empty DataFrame
Columns: [name, age, city, salary]
Index: []

In [33]:
import numpy as np
import pandas as pd

missing data

In [34]:
data ={
    'A':[1,2,np.nan],
    'B':[5,np.nan,np.nan],
    'C':[1,2,3]
}
df =pd.DataFrame(data)

In [35]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [36]:
df.isna()

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

In [37]:
df.isna().sum()

A    1
B    2
C    0
dtype: int64

In [38]:
df.isna().sum().sum()

np.int64(3)

In [39]:
df.dropna()

     A    B  C
0  1.0  5.0  1

In [40]:
df.isna().any()

A     True
B     True
C    False
dtype: bool

In [41]:
df.dropna(thresh=1)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

filling the missing data

In [42]:
df

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [43]:
df.fillna(0)

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

In [44]:
values ={'a':0,'b':100,'c':200}
df.fillna(value=values)

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [45]:
df.fillna(df.mean())

     A    B  C
0  1.0  5.0  1
1  2.0  5.0  2
2  1.5  5.0  3

merging 2 dataframes

In [46]:
import numpy as np
import pandas as pd

In [47]:
employees = pd.DataFrame({
    'emp_id':[1,2,3,4,5],
    'name':['john','rahul','shubham','rupesh',"shivam"],
    'age':[28,34,54,55,60],
})

#dataframe2 :salary information
salaries =pd.DataFrame({
    'emp_id':[1,2,3,4,5],
    'salary':['50000','30000','45000','34000','40000']
})

In [48]:
employees

   emp_id     name  age
0       1     john   28
1       2    rahul   34
2       3  shubham   54
3       4   rupesh   55
4       5   shivam   60

In [49]:
salaries

   emp_id salary
0       1  50000
1       2  30000
2       3  45000
3       4  34000
4       5  40000

In [50]:
pd.merge(employees,salaries,on='emp_id',how ='inner')

   emp_id     name  age salary
0       1     john   28  50000
1       2    rahul   34  30000
2       3  shubham   54  45000
3       4   rupesh   55  34000
4       5   shivam   60  40000

In [51]:
pd.merge(employees,salaries,on='emp_id',how ='outer')

   emp_id     name  age salary
0       1     john   28  50000
1       2    rahul   34  30000
2       3  shubham   54  45000
3       4   rupesh   55  34000
4       5   shivam   60  40000

In [52]:
pd.merge(employees,salaries,on='emp_id',how ='right')

   emp_id     name  age salary
0       1     john   28  50000
1       2    rahul   34  30000
2       3  shubham   54  45000
3       4   rupesh   55  34000
4       5   shivam   60  40000

concatination of 2 dataframe

In [53]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']

})

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']

})

In [54]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [55]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [56]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [57]:
pd.concat([df1,df2],axis =1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

joining 2 dataframe

In [58]:
df1 = pd.DataFrame({
 'name': ['rahul','shubham','rupesh']
},index =[1,2,3])

#second dataframe
df2 =pd.DataFrame({
    'score':[85,90,75]
},index =[2,3,4])

In [59]:
df1

      name
1    rahul
2  shubham
3   rupesh

In [60]:
df2

   score
2     85
3     90
4     75

In [61]:
df1.join(df2)

      name  score
1    rahul    NaN
2  shubham   85.0
3   rupesh   90.0

In [62]:
df1.join(df2,how='outer')

      name  score
1    rahul    NaN
2  shubham   85.0
3   rupesh   90.0
4      NaN   75.0

In [63]:
import numpy as np
import pandas as pd

groupby

In [64]:
data = {
    'categary':['A','B','C','A','B','C'],
    'store':['store1','store1','store2','store2','store1','store2'],
    'sales':[100,200,300,400,500,600],
    "Quantity":[10,20,30,40,50,60],
    'date':pd.date_range('2023-01-01',periods=6)
}
df = pd.DataFrame(data)

In [65]:
df

  categary   store  sales  Quantity       date
0        A  store1    100        10 2023-01-01
1        B  store1    200        20 2023-01-02
2        C  store2    300        30 2023-01-03
3        A  store2    400        40 2023-01-04
4        B  store1    500        50 2023-01-05
5        C  store2    600        60 2023-01-06

In [66]:
#group by category and calculate the sum of sales
Cat= df.groupby('categary')
Cat
for i, v in Cat:
  print(i)
  print(v)

A
  categary   store  sales  Quantity       date
0        A  store1    100        10 2023-01-01
3        A  store2    400        40 2023-01-04
B
  categary   store  sales  Quantity       date
1        B  store1    200        20 2023-01-02
4        B  store1    500        50 2023-01-05
C
  categary   store  sales  Quantity       date
2        C  store2    300        30 2023-01-03
5        C  store2    600        60 2023-01-06

In [67]:
df.groupby('categary')['sales'].sum()

categary
A    500
B    700
C    900
Name: sales, dtype: int64

In [68]:
#group by store and calculate the sum of sales
df.groupby('store')['sales'].sum()

store
store1     800
store2    1300
Name: sales, dtype: int64

In [69]:
#group by multtiple colums
#group by category and store
cat = df.groupby(['categary','store'])['sales'].sum()
cat

categary  store
A         store1    100
          store2    400
B         store1    700
C         store2    900
Name: sales, dtype: int64

aggregation

In [70]:
df['sales'].mean()
"""mean median mode min max std var"""

'mean median mode min max std var'

In [71]:
df['sales'].agg(['sum','mean','max','var'])

sum      2100.0
mean      350.0
max       600.0
var     35000.0
Name: sales, dtype: float64

In [72]:
import numpy as np
import pandas as pd

dataframe basis operation

In [73]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']

})

In [74]:
df1.shape

(3, 3)

In [75]:
df1.columns

Index(['A', 'B', 'C'], dtype='object')

In [76]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      object
 1   B       3 non-null      object
 2   C       3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

In [77]:
df1.describe()

         A   B   C
count    3   3   3
unique   3   3   3
top     A0  B0  C0
freq     1   1   1

dataframes applying functions

In [78]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [79]:
def square(x):
  return x==2

In [80]:
df1["B"].apply(square)

0    False
1    False
2    False
Name: B, dtype: bool

In [81]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [82]:
df1['D'] = df1["B"].apply(square)